# Generated by Django 6.0.2 on 2026-05-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CHANGE_PASSWORD', 'Changement mot de passe'), ('CREATION_DEMANDE', 'Création demande'), ('MODIFICATION_DEMANDE', 'Modification demande'), ('SOUMISSION_DEMANDE', 'Soumission demande'), ('APPROBATION_DEMANDE', 'Approbation demande'), ('REJET_DEMANDE', 'Rejet demande'), ('ANNULATION_DEMANDE', 'Annulation demande'), ('AJOUT_DOCUMENT', 'Ajout document'), ('SUPPRESSION_DOCUMENT', 'Suppression document'), ('MODIFICATION_PROFIL', 'Modification profil'), ('AJOUT_UTILISATEUR', 'Ajout utilisateur'), ('MODIFICATION_UTILISATEUR', 'Modification utilisateur'), ('SUPPRESSION_UTILISATEUR', 'Suppression utilisateur'), ('AJOUT_PAYS', 'Ajout pays'), ('AJOUT_SESSION', 'Ajout session'), ('OUVERTURE_SESSION', 'Ouverture session'), ('FERMETURE_SESSION', 'Fermeture session')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
