# Generated by Django 6.0.2 on 2026-05-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
