# Generated by Django 6.0.2 on 2026-05-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('DateVersion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibiliteEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dernier_stage_valide', models.BooleanField()),
                ('nb_stages_valide', models.BooleanField()),
                ('resultat', models.CharField(choices=[('ELIGIBLE', 'Éligible'), ('INELIGIBLE', 'Inéligible')], max_length=15)),
                ('date_verification', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(blank=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibilite', to='demandes.demande')),
            ],
        ),
        migrations.CreateModel(
            name='CritereEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('type_critere', models.CharField(choices=[('AUTO', 'Automatique'), ('MANUEL', 'Manuel')], default='MANUEL', max_length=10)),
                ('donnees_necessaires', models.JSONField(blank=True, default=list, help_text="Liste des données à saisir: ['experience_years', 'publications_count']")),
                ('description_donnees', models.JSONField(blank=True, default=dict, help_text='Description de chaque donnée pour le chercheur')),
                ('logique_verification', models.TextField(blank=True, help_text='Logique de vérification: experience_years > 5 AND publications_count >= 3')),
                ('grille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteres', to='evaluations.grilleevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseCritere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.JSONField(default=dict)),
                ('is_validated', models.BooleanField(blank=True, null=True)),
                ('justification', models.TextField(blank=True)),
                ('date_reponse', models.DateTimeField(auto_now_add=True)),
                ('critere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='evaluations.critereevaluation')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_criteres', to='demandes.demande')),
            ],
            options={
                'unique_together': {('demande', 'critere')},
            },
        ),
    ]
