# Generated by Django 6.0.2 on 2026-05-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('ENS', 'Enseignant Chercheur (MAA/MAB)'), ('DOC_NS', 'Doctorant Non-Salarié'), ('MC_B', 'Maître de Conférences Classe B'), ('MC_A', 'Maître de Conférences Classe A'), ('PROF', 'Professeur')], default='worker', help_text="Le code court utilisé par le moteur d'éligibilité", max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('directeur', models.CharField(blank=True, max_length=150, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='typeSejour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SSHN', 'Séjour Scientifique de Haut Niveau'), ('SPCTT', 'Stage de Perfectionnement CTT')], max_length=50, unique=True)),
                ('duree_min_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('duree_max_jours', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=20, unique=True)),
                ('date_ouverture', models.DateField()),
                ('date_fermeture', models.DateField()),
                ('etat', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée')], default='FERMEE', max_length=10)),
                ('nb_sejours_min', models.PositiveIntegerField(default=1)),
                ('annees_depuis_dernier_sejour', models.PositiveIntegerField(default=2)),
                ('grille_evaluation', models.ForeignKey(blank=True, help_text="Grille d'évaluation utilisée pour cette session", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='evaluations.grilleevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pays', to='parametres.zone')),
            ],
        ),
    ]
