# Generated by Django 6.0.2 on 2026-05-08 10:57

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.CharField(choices=[('CHERCHEUR', 'Chercheur'), ('ASSISTANT_DPGR', 'Assistant DPGR'), ('ADMIN_DPGR', 'Administrateur DPGR'), ('SUPER_ADMIN', 'Super Administrateur')], max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfilChercheur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Prof', 'Prof'), ('M.', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], max_length=10, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('email_personnel', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_fixe', models.CharField(blank=True, max_length=20, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('photo_profil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('equipe_recherche', models.CharField(blank=True, max_length=200, null=True)),
                ('matricule_esi', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('date_recrutement', models.DateField(blank=True, null=True)),
                ('email_professionnel', models.EmailField(blank=True, max_length=254, null=True)),
                ('bureau', models.CharField(blank=True, max_length=50, null=True)),
                ('domaine_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('mots_cles', models.TextField(blank=True, null=True)),
                ('biographie', models.TextField(blank=True, max_length=500, null=True)),
                ('google_scholar', models.URLField(blank=True, null=True)),
                ('researchgate', models.URLField(blank=True, null=True)),
                ('orcid', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('website_personnel', models.URLField(blank=True, null=True)),
                ('anciennete', models.IntegerField(default=0)),
                ('dernier_sejour', models.DateField(blank=True, null=True)),
                ('nombre_sejours_effectues', models.IntegerField(default=0)),
                ('total_jours_sejour', models.IntegerField(default=0)),
                ('nb_sejours_3_dernières_années', models.IntegerField(default=0)),
                ('nombre_inscri', models.IntegerField(default=1)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.grade')),
                ('laboratoire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametres.laboratoire')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
