# Generated by Django 6.0.2 on 2026-05-08 10:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoutDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cout', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50)),
                ('motif_rejet', models.CharField(blank=True, max_length=500, null=True)),
                ('notes_commentaires', models.TextField(blank=True, null=True)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demande', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('duree_jours', models.IntegerField(blank=True, null=True)),
                ('destination', models.CharField(max_length=200)),
                ('institution_accueil', models.CharField(max_length=200)),
                ('ville_accueil', models.CharField(max_length=100)),
                ('objectifs_scientifiques', models.TextField()),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('eligible', models.BooleanField(default=False)),
                ('score_total', models.FloatField(blank=True, null=True)),
                ('score_criteres', models.FloatField(blank=True, default=0, null=True)),
                ('recommandation_auto', models.TextField(blank=True, null=True)),
                ('montant_indemnite', models.FloatField(blank=True, null=True)),
                ('notes_internes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VERIFICATION_AUTOMATIQUE', 'Vérification automatique'), ('PREPARATION_CS', 'Préparation CS'), ('DELIBERATION_CS', 'Délibération CS'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('DEMANDE_ANNULATION', 'Demande annulation'), ('DELIBERATION_CS_FIN', 'Délibération CS fin'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=30)),
                ('attestation', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('type_document', models.CharField(max_length=100)),
                ('est_obligatoire', models.BooleanField(default=False)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichierRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('type_fichier', models.CharField(blank=True, choices=[('rapport', 'Rapport scientifique'), ('attestation', 'Attestation de présence'), ('justificatif', 'Justificatifs de transport'), ('photo', 'Photos/Visuels'), ('publication', 'Publications/Présentations')], max_length=20, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ancien_statut', models.CharField(blank=True, choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VERIFICATION_AUTOMATIQUE', 'Vérification automatique'), ('PREPARATION_CS', 'Préparation CS'), ('DELIBERATION_CS', 'Délibération CS'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('DEMANDE_ANNULATION', 'Demande annulation'), ('DELIBERATION_CS_FIN', 'Délibération CS fin'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], max_length=30, null=True)),
                ('nouveau_statut', models.CharField(blank=True, choices=[('BROUILLON', 'Brouillon'), ('SOUMISE', 'Soumise'), ('VERIFICATION_AUTOMATIQUE', 'Vérification automatique'), ('PREPARATION_CS', 'Préparation CS'), ('DELIBERATION_CS', 'Délibération CS'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Terminée'), ('DEMANDE_ANNULATION', 'Demande annulation'), ('DELIBERATION_CS_FIN', 'Délibération CS fin'), ('CLOTUREE', 'Clôturée'), ('ANNULEE', 'Annulée')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart_reelle', models.DateField(blank=True, null=True)),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectif_formation', models.BooleanField(default=False)),
                ('objectif_collaboration', models.BooleanField(default=False)),
                ('objectif_publication', models.BooleanField(default=False)),
                ('objectif_presentation', models.BooleanField(default=False)),
                ('objectif_autre', models.BooleanField(default=False)),
                ('objectif_autre_text', models.CharField(blank=True, max_length=255, null=True)),
                ('resultats', models.TextField(blank=True, null=True)),
                ('publications', models.CharField(blank=True, max_length=100, null=True)),
                ('collaborations', models.CharField(blank=True, max_length=100, null=True)),
                ('impact', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('points_positifs', models.TextField(blank=True, null=True)),
                ('difficultes', models.TextField(blank=True, null=True)),
                ('recommande', models.CharField(blank=True, choices=[('oui_fortement', 'Oui, fortement'), ('oui', 'Oui'), ('neutre', 'Neutre'), ('non', 'Non')], max_length=20, null=True)),
                ('civilite', models.CharField(blank=True, choices=[('Dr', 'Dr'), ('Prof', 'Prof'), ('M.', 'M.'), ('Mme', 'Mme'), ('Mlle', 'Mlle')], max_length=10, null=True)),
                ('nom_complet', models.CharField(blank=True, max_length=150, null=True)),
                ('date_signe', models.DateField(blank=True, null=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('commentaires_retour', models.TextField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('A_CORRIGER', 'À corriger')], default='EN_ATTENTE', max_length=20)),
            ],
        ),
    ]
