# Generated by Django 6.0.2 on 2026-05-08 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
        ('parametres', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='pris_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='chercheur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='users.profilchercheur'),
        ),
        migrations.AddField(
            model_name='demande',
            name='pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='parametres.pays'),
        ),
        migrations.AddField(
            model_name='demande',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='parametres.session'),
        ),
        migrations.AddField(
            model_name='demande',
            name='type_sejour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='parametres.typesejour'),
        ),
        migrations.AddField(
            model_name='decision',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='demandes.demande'),
        ),
        migrations.AddField(
            model_name='coutdemande',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cout', to='demandes.demande'),
        ),
        migrations.AddField(
            model_name='document',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demandes.demande'),
        ),
        migrations.AddField(
            model_name='log',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='demandes.demande'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rapport',
            name='demande',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='demandes.demande'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rapports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichierrapport',
            name='rapport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='demandes.rapport'),
        ),
    ]
