# Generated by Django 5.1.4 on 2026-05-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='score_final',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
