# Generated by Django 6.0.2 on 2026-05-08 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type_alerte', models.CharField(choices=[('CHANGEMENT_STATUT', 'Changement de statut'), ('CHANGEMENT_MOT_DE_PASSE', 'Changement de mot de passe'), ('OUVERTURE_SESSION', 'Ouverture de session'), ('FERMETURE_SESSION', 'Fermeture de session'), ('DEMANDE_SOUMISE', 'Demande soumise'), ('NOUVEAU_CHERCHEUR', 'Nouveau chercheur inscrit'), ('PREPARATION_CS', 'Demande prête pour le CS')], max_length=50)),
                ('est_lue', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='demandes.demande')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
